### ISSUE TITLE
Adding support for std_ulogic/vector

### ISSUE THREAD

**Issue by svenka3** [cfoge/VHLD_parse#1]
I needed a quick TB generator and I stumbled upon this nice, handy parse_vhdl. With some tweaks, I got std_ulogic working. Would you be interested in a PR? The fix was simply copy-patse and change logic/ulogic at few places. 

Thanks

**Comment by cfoge** [comment]
yes please, this is something that i am just chipping away in the background, any input would be greatly appreciated.
